import {
	TILE_SIZE,
	CANVAS_WIDTH,
	CANVAS_HEIGHT,
	ROWS,
	COLS,
} from "../constants.js";

export class Frog {
	constructor() {
		this.width = TILE_SIZE;
		this.height = TILE_SIZE;
		this.reset();
	}

	reset() {
		this.x = Math.floor(COLS / 2) * TILE_SIZE;
		this.y = CANVAS_HEIGHT - TILE_SIZE; // Bottom row
		this.highestY = this.y; // Track the highest row reached
		this.scoreEarned = 0; // Cumulative score generated by forward progress
		this.isOnLog = false;
		this.dx = 0; // Inherit speed from logs
	}

	update(input, dt) {
		let moved = false;

		if (input.justPressed.up) {
			this.y -= TILE_SIZE;
			moved = true;
		} else if (input.justPressed.down) {
			this.y += TILE_SIZE;
			moved = true;
		} else if (input.justPressed.left) {
			this.x -= TILE_SIZE;
			moved = true;
		} else if (input.justPressed.right) {
			this.x += TILE_SIZE;
			moved = true;
		}

		// Drifting laterally if on a log
		if (!moved && this.isOnLog) {
			this.x += this.dx * dt;
		}

		// Clamp to screen bounds
		if (this.x < 0) this.x = 0;
		if (this.x > CANVAS_WIDTH - this.width)
			this.x = CANVAS_WIDTH - this.width;
		if (this.y < 0) this.y = 0; // Can't go past the top
		if (this.y > CANVAS_HEIGHT - this.height)
			this.y = CANVAS_HEIGHT - this.height;

		this.checkScore();
	}

	checkScore() {
		// Did we move further up than ever before?
		if (this.y < this.highestY) {
			// How many rows did we advance?
			const scoreParams =
				(this.highestY - this.y) / TILE_SIZE;
			this.scoreEarned += scoreParams;
			this.highestY = this.y;
		}
	}

	// After adding score to Game, reset score flag
	consumeScore() {
		const val = this.scoreEarned;
		this.scoreEarned = 0;
		return val;
	}
}
